- name: Test connection
  hosts: "{{ env }}"
  remote_user: ubuntu 
  become: yes
  become_method: sudo
  gather_facts: false

  roles:
    - my_ping
    - install_docker
    - destroy_container
    - deploy_webapp
