---
- hosts: webservers 
  
  tasks:

    - name: Pull an image
      community.docker.docker_image:
        name: pacur/centos-7
        source: pull
        # Select platform for pulling. If not specified, will pull whatever docker prefers.
        pull:
          platform: amd64