---
    - hosts: webservers      
      become: yes
      become_method: sudo
      tasks:
        - name: Install pip
          apt: name=python-pip state=present
      
        - name: install docker-py
          pip: name=docker-py
      
        - name: Build Docker image from Dockerfile
          command: docker build -t web /var/lib/jenkins/workspace/docker_flask/docker/Dockerfile
        
        - name: Running the container
          docker_container:
            image: web:latest
            path: docker/Dockerfile
            state: running
            
        - name: Check if container is running
          shell: docker ps
