---
- hosts: webservers 
  tasks:

    - name: Create container
      community.docker.docker_container:
        name: web
        image: andriy900/webapp
        ports:
          - "5000:5000"
        restart_policy: always