---
- name: Test connection
  hosts: webservers 
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:

    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull