---
- hosts: webservers 
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:

    - name: Create a data container
      community.docker.docker_container:
        name: web-app
        image: andriy900/webapp
        ports:
          - "5000:5000"
        restart_policy: always