---
- hosts: "{{ env }}"
  remote_user: ubuntu 
  become: true
 
  gather_facts: false

  tasks:
    
  - name: stop all docker containers
    shell: docker stop $(docker ps -a -q)
    ignore_errors: true
    when: (docker ps -a -q) != 0
  - name: remove all docker containers
    shell: docker rm $(docker ps -a -q)
    ignore_errors: true
    when: (docker ps -a -q) != 0
  - name: remove all docker images
    shell: docker rmi $(docker images -q)
    ignore_errors: true
