---
- hosts: "{{ env }}"
  remote_user: ubuntu 
  become: true
  tasks:

   - name: Stop a container
     community.docker.docker_container:
       name: andriy900/webapp:master-11
       state: stopped
