---
- name: Test connection
  hosts: webservers 
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:

  - name: Install python
    raw: sudo apt-get -y install python-simplejson

  - name: Ping
    ping:

  - name: install dipendences
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  - name: add GPG
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: add repository docker
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
  - name: install docker
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  - name: enabled docker
    service:
      name: docker
      state: started
      enabled: yes
  

  handlers:
  - name: restart docker
    service: 
      name: docker 
      state: restarted