---
- hosts: webservers
  tasks:

    - name: Deploy WebApp
      community.docker.docker_container:
        name: web-app
        image: andriy900/webapp
        ports:
          - "5000:5000"
        restart_policy: always