---
- name: Test connection
  hosts: webservers 
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:

    - name: Pull default Docker image
      docker_image:
        name: andriy900/webapp
        source: pull