---
- name: Test connection
  hosts: webservers 
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:

  - name: Install python
    raw: sudo apt-get -y install python-simplejson

  - name: Ping
    ping:

  - name: Install Apache WebServer
    apt: name=apache2 state=latest

  - name: Start Apache
    service: name=apache2 state=started enabled=yes
