---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web
spec:
  selector:
    matchLabels:
      run: load-example
  replicas: 2
  template:
    metadata:
      labels:
        run: load-example
    spec:
      containers:
        - name: my-web
          image: ghost
          ports:
            - containerPort: 2368

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-web
  name: my-web
spec:
  ports:
  - nodePort: 32223
    port: 2368
    protocol: TCP
    targetPort: 2368
  selector:
    app: my-web
  type: NodePort
