---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web
spec:
  selector:
    matchLabels:
      run: load-example
  replicas: 1
  template:
    metadata:
      labels:
        run: load-example
    spec:
      containers:
        - name: my-web
          image: andriy900/webapp:master-latest
          ports:
            - containerPort: 5000
          env:
            - name: TEST_ENV
              value: $(mode)
            - name: "${LOGIN}"
#               value: $(LOGIN)
            - name: IMAGE_NAME
              value: $(IMAGE_NAME)
            - name: BRANCH_NAME
              value: $(BRANCH_NAME)
            - name: BUILD_NUMBER
              value:  $(BUILD_NUMBER)
            - name: LOGIN_DB
              value: admin
            - name: PASSW_DB
              value: "1234"
            - name: DB_LINC
              value:  server.com
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-web
  name: my-web
spec:
  ports:
  - nodePort: 32223
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: my-web
  type: NodePort
