---
# tasks file for deploy_webapp

    - name: Launch new webapp container
      community.docker.docker_container:
        name: "{{ env }}"
        image: "{{ docker_cred }}/{{ image_name }}:{{ branch_name }}-{{ build_number }}"
        state: present
        restart_policy: unless-stopped
        networks_cli_compatible: no
        container_default_behavior: compatibility
        exposed_ports:
          - "{{ port_number }}"
        ports:
          - "{{ port_number }}:5000"
#         volumes:
#           - /home/ubuntu/:/etc/nginx/
#         comparisons:
#           '*': ignore  # by default, ignore *all* options (including image)
#           env: strict 
        env: 
          TEST_ENV: "{{ TEST_ENV }}"
          LOGIN: "{{ docker_cred }}"
          IMAGE_NAME: "{{ image_name }}"
          BRANCH_NAME: "{{ branch_name }}"
          BUILD_NUMBER: "{{ build_number }}"
