---
# tasks file for deploy_webapp

    - name: Launch BLUE webapp container
      community.docker.docker_container:
        name: "{{ env }}-{{ mode }}"
        image: "{{ docker_cred }}/{{ image_name }}:{{ branch_name }}-{{ build_number }}"
        #image: "{{ docker_cred }}/{{ image_name }}:{{ branch_name }}-201"
        state: started
        recreate: no
        restart_policy: unless-stopped
        networks_cli_compatible: no
        container_default_behavior: compatibility
        exposed_ports:
          - "{{ port_number }}"
        ports:
          - "{{ port_number }}:5000"
        env: 
          #TEST_ENV: "{{ TEST_ENV }}"
          TEST_ENV: "{{ mode }}"
          LOGIN: "{{ docker_cred }}"
          IMAGE_NAME: "{{ image_name }}"
          BRANCH_NAME: "{{ branch_name }}"
          BUILD_NUMBER: "{{ build_number }}"
          LOGIN_DB: "{{ LOGIN_BLUE }}"
          PASSW_DB: "{{ PASSW_BLUE }}"
          DB_LINC: "{{ db_linc }}"
      when: {{ mode }} == "blue"
      
    - name: Launch GREEN webapp container
      community.docker.docker_container:
        name: "{{ env }}-{{ mode }}"
        image: "{{ docker_cred }}/{{ image_name }}:{{ branch_name }}-{{ build_number }}"
        #image: "{{ docker_cred }}/{{ image_name }}:{{ branch_name }}-201"
        state: started
        recreate: no
        restart_policy: unless-stopped
        networks_cli_compatible: no
        container_default_behavior: compatibility
        exposed_ports:
          - "{{ port_number }}"
        ports:
          - "{{ port_number }}:5000"
        env: 
          #TEST_ENV: "{{ TEST_ENV }}"
          TEST_ENV: "{{ mode }}"
          LOGIN: "{{ docker_cred }}"
          IMAGE_NAME: "{{ image_name }}"
          BRANCH_NAME: "{{ branch_name }}"
          BUILD_NUMBER: "{{ build_number }}"
          LOGIN_DB: "{{ LOGIN_GREEN }}"
          PASSW_DB: "{{ PASSW_GREEN }}"
          DB_LINC: "{{ db_linc }}"
      when: {{ mode }} == "green"
      
