apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    run: {{ .Release.Name }}
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    run: {{ .Release.Name }}
  type: NodePort
