# apiVersion: v1
# kind: Service
# metadata:
#   name: webapp-service
# spec:
#   selector:
#     app: web-app
#   ports:
#     - port: 5000
#       targetPort: 5000
#   type: NodePort
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    run: web-app
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    run: web-app

