---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app  #  {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      run: web-app
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        run: web-app
    spec:
      containers:
        - name:  web-app  #   {{ .Release.Name }}
          image: {{ .Values.container.image }}
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            {{- range $key, $value := .Values.envmap }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}



