---
# tasks file for deploy_nginx

    - name: Launch new webapp container
      community.docker.docker_container:
        name: nginxapp
        image: nginx
        state: started
        restart_policy: unless-stopped
        networks_cli_compatible: no
        container_default_behavior: compatibility
        exposed_ports:
          - 5001
        ports:
          - 5001:5001
          
    - name: copy nginx configuration to remote host
      template: src=nginx.conf dest=nginx.conf      
      
    - name: copy nginx.conf
      become: yes
      command: docker cp nginx.conf nginxapp:/etc/nginx/nginx.conf

    - name: Launch new webapp container
      community.docker.docker_container:
        name: nginxapp
        image: nginx
        state: started
        restart: yes
