---
# tasks file for deploy_nginx

    - name: Launch new nginx container
      community.docker.docker_container:
        name: nginxapp
        image: nginx
        state: started
        restart_policy: unless-stopped
        networks_cli_compatible: no
        container_default_behavior: compatibility
        exposed_ports:
          - 5001
        ports:
          - 5001:5001
        volumes:
          - ansible_env.HOME:/etc/nginx/ 
          #- "{{ ansible_env.HOME }}:/etc/nginx/" 
          
    - name: copy nginx configuration to remote host
      template: src=ansible_env.HOME/nginx.conf dest=ansible_env.HOME/nginx.conf  
      
    - debug:
      var: ansible_env.HOME
      
    - debug:
      var: ansible_enp0s3.ipv4.address
      
    - name: Restart nginx container
      community.docker.docker_container:
        name: nginxapp
        image: nginx
        state: started
        restart: yes
